spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/stack-crud
    username: stack-crud-owner
    password: stack-crud-owner
  flyway:
    enable: false
    url: jdbc:postgresql://localhost:5432/stack-crud
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    out-of-order: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://docker-stack-crud:docker-stack-crud@localhost:27017/docker-stack-crud?authSource=docker-stack-crud
